sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dpmidyett/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dpmidyett/docker-react npm run test